swagger: "2.0"
info:
  description: "This is a sample flight rating API."
  version: "1.0.0"
  title: "Sample Flight Rating API"
  contact:
    email: "yannick.adam@gmail.com"
  license:
    name: "BSD-3"
    url: "https://opensource.org/licenses/BSD-3-Clause"
host: "ratings.localhost.io"
basePath: "/v1"
tags:
- name: "rating"
  description: "The main and only resource"
schemes:
- "https"
- "http"
consumes:
- application/json
produces:
- application/json
paths:
  /rating/{flightId}:
    get:
      tags:
      - "rating"
      summary: "Returns the rating for this flight"
      description: "Returns the rating for this flight"
      operationId: "getRatingForFlight"
      parameters:
      - name: "flightId"
        in: "path"
        description: "ID of flight to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Rating"
        400:
          description: "Invalid input data"
        404:
          description: "No rating for this flight"
    post:
      tags:
      - "rating"
      summary: "Adds a rating to a flight"
      description: ""
      operationId: "addRatingToFlight"
      parameters:
      - name: "flightId"
        in: "path"
        description: "ID of the flights we want to rate"
        required: true
        type: "string"
      - name: "ratingBody"
        in: "body"
        description: "The rating to give to the flight."
        required: true
        schema:
          type: object
          required:
          - rating
          properties:
            rating:
              type: number
              description: "A value between 1 and 5 stars."
      responses:
        201:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Rating"
        400:
          description: "Invalid input"

definitions:
  Rating:
    type: object
    required:
    - flightId
    - rating
    properties:
      flightId:
        type: string
        description: "A flight ID is composed of [AN2/Airline Code][N1-4 / Flight number] (ie: LH2148)"
      rating:
        type: number
        description: "A rating has a value between 1 and 5. (ie: 4.38)"
      votes:
        type: number
        description: The number of votes